Repository Secure-Compliance-Solutions-LLC/GVM-Docker, pull requests merged in 2021-07, with the labels that each got.

#215 Add Support for Swarm Secrets
  Dockerfile
  scripts/entrypoint.sh
  scripts/start.sh
Labels: documentation, enhancement

#228 GitHub action dexus 2
  .github/workflows/docker-publish.yml
Labels: Priority:High, bug, enhancement

#233 fix(supervisord): gsad binary path correction
  config/supervisord.conf
Labels: bug

#236 Release v21.4.2-v2
  .dockerignore
  .github/workflows/docker-publish.yml
  Dockerfile
  config/sshd_config
  config/supervisord.conf
Labels: Priority:High, bug

#239 v21.4.2-v3
  .github/workflows/docker-publish.yml
  scripts/start.sh
  scripts/sync-all.sh
Labels: Priority:High, bug, enhancement
